# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mih', [dirname(__file__)])
        except ImportError:
            import _mih
            return _mih
        if fp is not None:
            try:
                _mod = imp.load_module('_mih', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mih = swig_import_helper()
    del swig_import_helper
else:
    import _mih
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_mih.BIT_NUM_swigconstant(_mih)
BIT_NUM = _mih.BIT_NUM

_mih.BYTE_NUM_swigconstant(_mih)
BYTE_NUM = _mih.BYTE_NUM

_mih.SLICE_NUM_swigconstant(_mih)
SLICE_NUM = _mih.SLICE_NUM

_mih.RADIUS_swigconstant(_mih)
RADIUS = _mih.RADIUS

def cmp(s1, s2):
    return _mih.cmp(s1, s2)
cmp = _mih.cmp

def readdata():
    return _mih.readdata()
readdata = _mih.readdata

def getSliceHashCode(b, begin):
    return _mih.getSliceHashCode(b, begin)
getSliceHashCode = _mih.getSliceHashCode

def getCombinationPos(m):
    return _mih.getCombinationPos(m)
getCombinationPos = _mih.getCombinationPos

def recurGetCombination(i, m, temp, result):
    return _mih.recurGetCombination(i, m, temp, result)
recurGetCombination = _mih.recurGetCombination

def getRNeighbourPos(pos):
    return _mih.getRNeighbourPos(pos)
getRNeighbourPos = _mih.getRNeighbourPos

def hammingDistance(b1, b2):
    return _mih.hammingDistance(b1, b2)
hammingDistance = _mih.hammingDistance
class HashTable(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HashTable, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HashTable, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mih.new_HashTable()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _mih.delete_HashTable
    __del__ = lambda self: None

    def addItem(self, record, pos):
        return _mih.HashTable_addItem(self, record, pos)

    def getBucket(self, pos):
        return _mih.HashTable_getBucket(self, pos)

    def size(self):
        return _mih.HashTable_size(self)
HashTable_swigregister = _mih.HashTable_swigregister
HashTable_swigregister(HashTable)

class MihSearcher(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MihSearcher, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MihSearcher, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _mih.new_MihSearcher()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _mih.delete_MihSearcher
    __del__ = lambda self: None

    def searchRecord(self, record):
        return _mih.MihSearcher_searchRecord(self, record)
MihSearcher_swigregister = _mih.MihSearcher_swigregister
MihSearcher_swigregister(MihSearcher)

# This file is compatible with both classic and new-style classes.


